### ISSUE TITLE
When will be the next release?

### ISSUE THREAD

**Issue by whizkid79** [sylvainlaurent/yaml-json-validator-maven-plugin#18]
Hi @sylvainlaurent,
Thanks for your great work here. Can you estimate when the next release will be? We need features which are already in master but not yet released.
Thanks,
Peter

**Comment by whizkid79** [comment]
ping?

**Comment by sylvainlaurent** [comment]
just released 1.0.3. Sorry for the delay.

**Comment by whizkid79** [comment]
thank you!
